# Generated by Django 3.2.5 on 2021-07-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
