# Generated by Django 3.2.5 on 2021-07-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='Destonation',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Кант', 'Кант'), ('Балыкчи', 'Балыкчи'), ('Каракол', 'Каракол'), ('Талас', 'Талас'), ('Нарын', 'Нарын'), ('Джалал-абад', 'Джалал-абад'), ('Ош', 'Ош'), ('Баткен', 'Баткен')], default=1, max_length=100, verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='Start',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Кант', 'Кант'), ('Балыкчи', 'Балыкчи'), ('Каракол', 'Каракол'), ('Талас', 'Талас'), ('Нарын', 'Нарын'), ('Джалал-абад', 'Джалал-абад'), ('Ош', 'Ош'), ('Баткен', 'Баткен')], default=1, max_length=100, verbose_name='Пункт отправки'),
        ),
    ]
