# Generated by Django 3.2.5 on 2021-08-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfRegister', models.DateField(verbose_name='дата поездки(год-месяц-день)')),
                ('Description', models.TextField(verbose_name='Примечание')),
                ('NumOfSits', models.IntegerField(verbose_name='Колиество мест')),
                ('Start', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Кант', 'Кант'), ('Балыкчи', 'Балыкчи'), ('Каракол', 'Каракол'), ('Талас', 'Талас'), ('Нарын', 'Нарын'), ('Джалал-абад', 'Джалал-абад'), ('Ош', 'Ош'), ('Баткен', 'Баткен')], default=1, max_length=100, verbose_name='Пункт отправки')),
                ('Destonation', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Кант', 'Кант'), ('Балыкчи', 'Балыкчи'), ('Каракол', 'Каракол'), ('Талас', 'Талас'), ('Нарын', 'Нарын'), ('Джалал-абад', 'Джалал-абад'), ('Ош', 'Ош'), ('Баткен', 'Баткен')], default=1, max_length=100, verbose_name='Пункт назначения')),
                ('Price', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinfo')),
            ],
        ),
    ]
