# Generated by Django 3.2.5 on 2021-08-29 12:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210827_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Номер телефона (e.g. +12125552368)'),
        ),
    ]
